// <auto-generated />
using System;
using ElectronicsStore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElectronicsStore.API.Migrations
{
    [DbContext(typeof(ElectronicsStoreDbContext))]
    [Migration("20260128160306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChiTiet"));

                    b.Property<int?>("DonHangMaDH")
                        .HasColumnType("integer");

                    b.Property<decimal>("GiaTaiThoiDiem")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("GiamGiaCungChiTiet")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MaDH")
                        .HasColumnType("integer");

                    b.Property<int>("MaSP")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SanPhamMaSP")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("DonHangMaDH");

                    b.HasIndex("SanPhamMaSP");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.DanhGiaSanPham", b =>
                {
                    b.Property<int>("MaDG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDG"));

                    b.Property<bool>("CoDienTieuDung")
                        .HasColumnType("boolean");

                    b.Property<int>("DemSao")
                        .HasColumnType("integer");

                    b.Property<bool>("DuocDuyet")
                        .HasColumnType("boolean");

                    b.Property<int>("MaND")
                        .HasColumnType("integer");

                    b.Property<int>("MaSP")
                        .HasColumnType("integer");

                    b.Property<int?>("NguoiDungMaND")
                        .HasColumnType("integer");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.Property<int?>("SanPhamMaSP")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuotThichChu")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SuaDoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ThemTrongDB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MaDG");

                    b.HasIndex("NguoiDungMaND");

                    b.HasIndex("SanPhamMaSP");

                    b.ToTable("DanhGiaSanPhams");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.DanhMucSanPham", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("HinhAnh")
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SuaDoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ThemTrongDB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMucSanPhams");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.DonHang", b =>
                {
                    b.Property<int>("MaDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDH"));

                    b.Property<string>("DiaChiGiaoHang")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("MaDonHangGoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaND")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTaoDon")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiDungMaND")
                        .HasColumnType("integer");

                    b.Property<decimal>("PhiVanChuyen")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SodTLienHe")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ThanhPhoPhuong")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TienGiamGia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TongGiaSauGiam")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("TongGiaTruocGiam")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("TrangThaiDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaDH");

                    b.HasIndex("NguoiDungMaND");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaGioHang"));

                    b.Property<int>("MaND")
                        .HasColumnType("integer");

                    b.Property<int>("MaSP")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiDungMaND")
                        .HasColumnType("integer");

                    b.Property<int?>("SanPhamMaSP")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("MaGioHang");

                    b.HasIndex("NguoiDungMaND");

                    b.HasIndex("SanPhamMaSP");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.LichSuDonHang", b =>
                {
                    b.Property<int>("MaLS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLS"));

                    b.Property<int?>("DonHangMaDH")
                        .HasColumnType("integer");

                    b.Property<string>("LyDo")
                        .HasColumnType("text");

                    b.Property<int>("MaDH")
                        .HasColumnType("integer");

                    b.Property<int?>("MaNguoiCapNhat")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiDungMaND")
                        .HasColumnType("integer");

                    b.Property<string>("TrangThaiCu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrangThaiMoi")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaLS");

                    b.HasIndex("DonHangMaDH");

                    b.HasIndex("NguoiDungMaND");

                    b.ToTable("LichSuDonHangs");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.LichSuThanhToan", b =>
                {
                    b.Property<int>("MaLS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLS"));

                    b.Property<int?>("DonHangMaDH")
                        .HasColumnType("integer");

                    b.Property<string>("GhiChuLoi")
                        .HasColumnType("text");

                    b.Property<int>("MaDH")
                        .HasColumnType("integer");

                    b.Property<int>("MaND")
                        .HasColumnType("integer");

                    b.Property<string>("MaThamChieu")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiDungMaND")
                        .HasColumnType("integer");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("SoTienThanhToan")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("TrangThaiGD")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaLS");

                    b.HasIndex("DonHangMaDH");

                    b.HasIndex("NguoiDungMaND");

                    b.ToTable("LichSuThanhToans");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.MaKhuyenMai", b =>
                {
                    b.Property<int>("MaKM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKM"));

                    b.Property<decimal?>("GiaTriDonHangToiThieu")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("GiaTriGiam")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GiaTriGiamToiDa")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("GioiHanSoLuotSuDung")
                        .HasColumnType("integer");

                    b.Property<string>("KieuGiam")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SoLuotSuDung")
                        .HasColumnType("integer");

                    b.Property<string>("TenChienDich")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ThemTrongDB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("MaKM");

                    b.ToTable("MaKhuyenMais");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.NguoiDung", b =>
                {
                    b.Property<int>("MaND")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaND"));

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("boolean");

                    b.Property<string>("DiaChiChiTiet")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DiaChiMacDinh")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LaQuanTriVien")
                        .HasColumnType("boolean");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("QuocGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("SuaDoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenDayDu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ThanhPho")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ThemTrongDB")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaND");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.NhaSanXuat", b =>
                {
                    b.Property<int>("MaNhaSX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhaSX"));

                    b.Property<string>("DatNuoc")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("SuaDoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenNhaSX")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ThemTrongDB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("MaNhaSX");

                    b.ToTable("NhaSanXuats");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.SanPham", b =>
                {
                    b.Property<int>("MaSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaSP"));

                    b.Property<decimal>("DanhGiaXepHang")
                        .HasColumnType("decimal(2,1)");

                    b.Property<int?>("DanhMucMaDanhMuc")
                        .HasColumnType("integer");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("GiaGiamGia")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("text");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("integer");

                    b.Property<int?>("MaNhaSX")
                        .HasColumnType("integer");

                    b.Property<string>("MoTaChiTiet")
                        .HasColumnType("text");

                    b.Property<int?>("NhaSXMaNhaSX")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuongTonKho")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuotDanhGia")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuotXem")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SuaDoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ThemTrongDB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ThongTinKyThuat")
                        .HasColumnType("text");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("MaSP");

                    b.HasIndex("DanhMucMaDanhMuc");

                    b.HasIndex("NhaSXMaNhaSX");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.ThongKeLuotXem", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTK"));

                    b.Property<int?>("MaND")
                        .HasColumnType("integer");

                    b.Property<int>("MaSP")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayXem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NguoiDungMaND")
                        .HasColumnType("integer");

                    b.Property<int?>("SanPhamMaSP")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuotXemTrongNgay")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ThemTrongDB")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaTK");

                    b.HasIndex("NguoiDungMaND");

                    b.HasIndex("SanPhamMaSP");

                    b.ToTable("ThongKeLuotXems");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("ElectronicsStore.API.Models.Entities.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangMaDH");

                    b.HasOne("ElectronicsStore.API.Models.Entities.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("SanPhamMaSP");

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.DanhGiaSanPham", b =>
                {
                    b.HasOne("ElectronicsStore.API.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("NguoiDungMaND");

                    b.HasOne("ElectronicsStore.API.Models.Entities.SanPham", "SanPham")
                        .WithMany("DanhGias")
                        .HasForeignKey("SanPhamMaSP");

                    b.Navigation("NguoiDung");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.DonHang", b =>
                {
                    b.HasOne("ElectronicsStore.API.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("DonHangs")
                        .HasForeignKey("NguoiDungMaND");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.GioHang", b =>
                {
                    b.HasOne("ElectronicsStore.API.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("GioHangs")
                        .HasForeignKey("NguoiDungMaND");

                    b.HasOne("ElectronicsStore.API.Models.Entities.SanPham", "SanPham")
                        .WithMany("GioHangs")
                        .HasForeignKey("SanPhamMaSP");

                    b.Navigation("NguoiDung");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.LichSuDonHang", b =>
                {
                    b.HasOne("ElectronicsStore.API.Models.Entities.DonHang", "DonHang")
                        .WithMany("LichSuDonHangs")
                        .HasForeignKey("DonHangMaDH");

                    b.HasOne("ElectronicsStore.API.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("LichSuDonHangs")
                        .HasForeignKey("NguoiDungMaND");

                    b.Navigation("DonHang");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.LichSuThanhToan", b =>
                {
                    b.HasOne("ElectronicsStore.API.Models.Entities.DonHang", "DonHang")
                        .WithMany("LichSuThanhToans")
                        .HasForeignKey("DonHangMaDH");

                    b.HasOne("ElectronicsStore.API.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("LichSuThanhToans")
                        .HasForeignKey("NguoiDungMaND");

                    b.Navigation("DonHang");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.SanPham", b =>
                {
                    b.HasOne("ElectronicsStore.API.Models.Entities.DanhMucSanPham", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucMaDanhMuc");

                    b.HasOne("ElectronicsStore.API.Models.Entities.NhaSanXuat", "NhaSX")
                        .WithMany("SanPhams")
                        .HasForeignKey("NhaSXMaNhaSX");

                    b.Navigation("DanhMuc");

                    b.Navigation("NhaSX");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.ThongKeLuotXem", b =>
                {
                    b.HasOne("ElectronicsStore.API.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungMaND");

                    b.HasOne("ElectronicsStore.API.Models.Entities.SanPham", "SanPham")
                        .WithMany("ThongKes")
                        .HasForeignKey("SanPhamMaSP");

                    b.Navigation("NguoiDung");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.DanhMucSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("LichSuDonHangs");

                    b.Navigation("LichSuThanhToans");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");

                    b.Navigation("LichSuDonHangs");

                    b.Navigation("LichSuThanhToans");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.NhaSanXuat", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("ElectronicsStore.API.Models.Entities.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DanhGias");

                    b.Navigation("GioHangs");

                    b.Navigation("ThongKes");
                });
#pragma warning restore 612, 618
        }
    }
}
